apiVersion: v1
kind: Service
metadata:
  name: cat
  namespace: cat
spec:
  selector:
    run: cat
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer    
